"""The sixth cost-blind census: every named fallacy in the IEP's Fallacies article.

Dowden's article (Internet Encyclopedia of Philosophy) is one of the five taxonomies
Greenwell et al. surveyed, fetched whole on 2026-08-27. Its own count sentence,
verbatim: "The list of fallacies below contains 231 names of the most common
fallacies, and it provides brief explanations and examples of each of them." Its
definition, verbatim: "A fallacy is a kind of error in reasoning."

Routes, per the estate's criterion (a rule detects a reasoning flaw, never demands
paperwork):

  covered  an existing decider convicts this flaw in some lane; the tag names it
  zero     decidable from the account graph with no new vocabulary
  vocab    needs a fact the graph does not carry; walton:<scheme> tags the rows the
           structured-argumentation formalism would decide uniformly
  judge    stays with a reader
  alias    another name for a row censused once; the tag points at it

The alias share is itself a finding: the list names the same flaw under Latin,
English and colloquial titles, so 231 names cover far fewer distinct patterns --
the printed counts say how many.
"""

from __future__ import annotations

SOURCE = "B. Dowden, Fallacies, Internet Encyclopedia of Philosophy (fetched 2026-08-27)"
SOURCE_URL = "https://iep.utm.edu/fallacy/"
SOURCE_COUNT = 231

C, Z, V, J, A = "covered", "zero", "vocab", "judge", "alias"

CENSUS = {
    "Abusive Ad Hominem": (J, "ethotic; walton:ethotic1 under structured"),
    "Accent": (J, "spoken emphasis; SR census row"),
    "Accentus": (A, "-> Accent"),
    "Accident": (J, "SR census row"),
    "Ad Baculum": (A, "-> Appeal to Force"),
    "Ad Consequentiam": (A, "-> Appeal to Consequence"),
    "Ad Crumenum": (A, "-> Appeal to Money"),
    "Ad Hoc Rescue": (J, "rescue-by-revision; the ledger roll catches the in-place half"),
    "Ad Hominem": (J, "walton:ethotic1/2 under structured"),
    "Ad Hominem Circumstantial": (A, "-> Circumstantial Ad Hominem"),
    "Ad Ignorantiam": (A, "-> Appeal to Ignorance"),
    "Ad Misericordiam": (A, "-> Appeal to Pity"),
    "Ad Novitatem": (J, "novelty as warrant"),
    "Ad Numerum": (A, "-> Appeal to the People"),
    "Ad Populum": (A, "-> Appeal to the People"),
    "Ad Verecundiam": (A, "-> Appeal to Authority"),
    "Affirming the Consequent": (C, "the-premises-entail-the-conclusion-or-they-do-not"),
    "Against the Person": (A, "-> Ad Hominem"),
    "All-or-Nothing": (A, "-> False Dilemma"),
    "Ambiguity": (J, "SR census row"),
    "Amphiboly": (J, "SR census row"),
    "Anecdotal Evidence": (V, "sample metadata; measurement half: a-corpus-names-its-assembly"),
    "Anthropomorphism": (J, "category error in content"),
    "Appeal to Authority": (V, "walton:expert_opinion; its exceptions are the CQs"),
    "Appeal to Consequence": (V, "walton:negative_consequences/positive_consequences"),
    "Appeal to Emotions": (J, "accounts carry no emotional appeals; reply prose is a reading"),
    "Appeal to Force": (J, "coercion, not inference"),
    "Appeal to Ignorance": (C, "absence-of-evidence-concludes-nothing"),
    "Appeal to Money": (J, "irrelevant-authority family"),
    "Appeal to Past Practice": (A, "-> Common Practice"),
    "Appeal to Pity": (J, "emotional appeal"),
    "Appeal to Snobbery": (J, "emotional appeal"),
    "Appeal to the Gallery": (A, "-> Appeal to the People"),
    "Appeal to the Masses": (A, "-> Appeal to the People"),
    "Appeal to the Mob": (A, "-> Appeal to the People"),
    "Appeal to the People": (J, "popularity as warrant"),
    "Appeal to the Stick": (A, "-> Appeal to Force"),
    "Appeal to Traditional Wisdom": (A, "-> Common Practice"),
    "Appeal to Unqualified Authority": (A, "-> Appeal to Authority"),
    "Appeal to Vanity": (J, "emotional appeal"),
    "Argument from Ignorance": (A, "-> Appeal to Ignorance"),
    "Argument from Outrage": (J, "emotional appeal"),
    "Argument from Popularity": (A, "-> Appeal to the People"),
    "Argumentum Ad": (A, "umbrella entry for the Latin names"),
    "Argumentum Consensus Gentium": (A, "-> Common Belief"),
    "Availability Heuristic": (J, "psychology of the arguer"),
    "Avoiding the Issue": (J, "dialogue-level relevance"),
    "Avoiding the Question": (A, "-> Avoiding the Issue"),
    "Bad Seed": (J, "genetic family; origins as refutation"),
    "Bald Man": (A, "-> Heap"),
    "Bandwagon": (A, "-> Appeal to the People"),
    "Begging the Question": (C, "no-claim-supports-itself"),
    "Beside the Point": (A, "-> Irrelevant Conclusion"),
    "Biased Generalizing": (A, "-> Biased Sample"),
    "Biased Sample": (V, "sample metadata; measurement half: a-corpus-names-its-assembly"),
    "Biased Statistics": (A, "-> Biased Sample"),
    "Bifurcation": (A, "-> False Dilemma"),
    "Black-or-White": (A, "-> False Dilemma"),
    "Caricaturization": (A, "-> Straw Man"),
    "Changing the Question": (J, "dialogue-level"),
    "Cherry-Picking": (J, "in-graph half: counter-evidence-is-answered; availability outside"),
    "Circular Reasoning": (A, "-> Begging the Question"),
    "Circumstantial Ad Hominem": (J, "ethotic; walton:ethotic under structured"),
    "Clouding the Issue": (J, "dialogue-level"),
    "Common Belief": (J, "popularity as warrant"),
    "Common Cause": (V, "causal vocabulary; walton:correlation_to_cause exception"),
    "Common Practice": (J, "practice as warrant"),
    "Complex Question": (J, "accounts carry no questions; SR many-questions row"),
    "Composition": (J, "part-whole vocabulary absent; Greenwell routed it to a reader too"),
    "Confirmation Bias": (J, "psychology of the arguer"),
    "Confusing an Explanation with an Excuse": (J, "speech-act distinction"),
    "Conjunction": (V, "probability vocabulary"),
    "Consensus Gentium": (A, "-> Common Belief"),
    "Consequence": (A, "-> Appeal to Consequence"),
    "Contextomy": (J, "quote real, context distorting; anchor covers the fabrication half"),
    "Converse Accident": (J, "generalizing from the exception; SR secundum-quid family"),
    "Cover-up": (J, "suppression outside the graph"),
    "Cum Hoc Ergo Propter Hoc": (A, "-> False Cause"),
    "Curve Fitting": (V, "prespecification: a-protocol-is-an-artifact-before-the-run"),
    "Definist": (J, "definition smuggling"),
    "Denying the Antecedent": (C, "the-premises-entail-the-conclusion-or-they-do-not"),
    "Digression": (J, "dialogue-level"),
    "Disregarding Known Science": (J, "external evidence availability"),
    "Distraction": (A, "-> Red Herring"),
    "Division": (J, "part-whole; converse of Composition"),
    "Domino": (A, "-> Slippery Slope"),
    "Double Standard": (J, "consistency across cases; case vocabulary absent"),
    "Either/Or": (A, "-> False Dilemma"),
    "Equivocation": (J, "SR ambiguity row; the four-term surface is covered by derive()"),
    "Etymological": (J, "meaning from origin"),
    "Every and All": (Z, "quantifier-order confusion over categorical forms; Z3 decides"),
    "Exaggeration": (J, "degree in content"),
    "Excluded Middle": (A, "-> False Dilemma"),
    "False Analogy": (V, "walton:analogy; its exceptions are the CQs"),
    "False Balance": (J, "weighting of sources"),
    "False Cause": (V, "causal vocabulary; walton:correlation_to_cause/cause_to_effect"),
    "False Dichotomy": (A, "-> False Dilemma"),
    "False Dilemma": (V, "exhaustiveness of stated alternatives is a world-fact"),
    "False Equivalence": (J, "comparison judgment"),
    "Far-Fetched Hypothesis": (V, "walton:abduction exception: a more coherent explanation exists"),
    "Faulty Comparison": (A, "-> False Analogy"),
    "Faulty Generalization": (A, "-> Hasty Generalization"),
    "Faulty Motives": (J, "ethotic"),
    "Formal": (C, "the-premises-entail-the-conclusion-or-they-do-not, whole family"),
    "Four Terms": (C, "derive() refuses premises that never meet"),
    "Gambler's": (V, "probability vocabulary"),
    "Genetic": (J, "origins as refutation"),
    "Group Think": (J, "psychology of the arguer"),
    "Guilt by Association": (J, "ethotic"),
    "Hasty Conclusion": (A, "-> Hasty Generalization"),
    "Hasty Generalization": (V, "sample metadata; measurement half: the calibration-size laws"),
    "Heap": (J, "vagueness; line-drawing in content"),
    "Hedging": (J, "the claims lane's qualifier law reads the filed half"),
    "Hooded Man": (J, "intensional context"),
    "Hyperbolic Discounting": (J, "preference structure"),
    "Hypostatization": (A, "-> Reification"),
    "Ideology-Driven Argumentation": (J, "psychology of the arguer"),
    "Ignoratio Elenchi": (A, "-> Irrelevant Conclusion"),
    "Ignoring a Common Cause": (A, "-> Common Cause"),
    "Ignoring Inconvenient Data": (J, "in-graph half: counter-evidence-is-answered"),
    "Improper Analogy": (A, "-> False Analogy"),
    "Incomplete Evidence": (J, "availability outside the graph"),
    "Inconsistency": (Z, "premises jointly unsatisfiable; one Z3 call decides"),
    "Inductive Conversion": (C, "illicit conversion fails entailment; Z3 refutes it"),
    "Insufficient Statistics": (A, "-> Small Sample"),
    "Intensional": (J, "substitution in opaque contexts"),
    "Invalid Reasoning": (A, "-> Formal"),
    "Irrelevant Conclusion": (C, "the RA names its conclusion; Z3 judges that one"),
    "Irrelevant Reason": (A, "-> Irrelevant Conclusion"),
    "Is-Ought": (V, "normative marker on propositions"),
    "Jumping to Conclusions": (A, "-> Hasty Generalization"),
    "Lack of Proportion": (J, "weighting in content"),
    "Line-Drawing": (A, "-> Heap"),
    "Loaded Language": (J, "connotation in prose"),
    "Loaded Question": (A, "-> Complex Question"),
    "Logic Chopping": (J, "dialogue-level quibbling"),
    "Logical": (A, "-> Formal"),
    "Lying": (J, "the anchor law catches the record-contradicting half"),
    "Maldistributed Middle": (A, "-> Undistributed Middle"),
    "Many Questions": (A, "-> Complex Question"),
    "Misconditionalization": (Z, "conditional scope over categorical forms; Z3 decides"),
    "Misleading Accent": (A, "-> Accent"),
    "Misleading Vividness": (J, "salience vs base rate; a-cause-is-weighed reads the filed half"),
    "Misplaced Burden of Proof": (J, "dialogue-level; the absence law reads the in-graph half"),
    "Misplaced Concreteness": (A, "-> Reification"),
    "Misrepresentation": (J, "fabrication half covered by the anchor law"),
    "Missing the Point": (A, "-> Irrelevant Conclusion"),
    "Mob Appeal": (A, "-> Appeal to the People"),
    "Modal": (Z, "modal scope over categorical necessity; the entailment layer decides"),
    "Monte Carlo": (A, "-> Gambler's"),
    "Name Calling": (J, "ethotic"),
    "Naturalistic": (V, "normative marker; Is-Ought family"),
    "Neglecting a Common Cause": (A, "-> Common Cause"),
    "No Middle Ground": (A, "-> False Dilemma"),
    "No True Scotsman": (J, "redefinition mid-argument; the ledger roll catches the recorded half"),
    "Non Causa Pro Causa": (A, "-> False Cause"),
    "Non Sequitur": (C, "the-premises-entail-the-conclusion-or-they-do-not"),
    "Obscurum per Obscurius": (J, "explanation quality"),
    "One-Sidedness": (J, "in-graph half: counter-evidence-is-answered"),
    "Opposition": (J, "partisan source-weighting"),
    "Outrage Argument from": (A, "-> Argument from Outrage"),
    "Over-Fitting": (A, "-> Curve Fitting"),
    "Overgeneralization": (A, "-> Hasty Generalization"),
    "Oversimplification": (J, "Greenwell routed the model half covered; the prose half stays"),
    "Past Practice": (A, "-> Common Practice"),
    "Pathetic": (J, "pathetic fallacy; Anthropomorphism family"),
    "Peer Pressure": (A, "-> Appeal to the People"),
    "Perfectionist": (J, "standard-setting in content"),
    "Persuasive Definition": (J, "definition smuggling"),
    "Petitio Principii": (A, "-> Begging the Question"),
    "Poisoning the Well": (J, "ethotic, preemptive"),
    "Popularity Argument from": (A, "-> Appeal to the People"),
    "Post Hoc": (V, "causal vocabulary; walton:correlation_to_cause"),
    "Prejudicial Language": (A, "-> Loaded Language"),
    "Proof Surrogate": (J, "the anchor law is this for grounded premises; the prose half stays"),
    "Prosecutor's": (V, "probability vocabulary; conditional inversion"),
    "Prosody": (A, "-> Accent"),
    "Quantifier Shift": (Z, "quantifier-order over categorical forms; Z3 decides"),
    "Question Begging": (A, "-> Begging the Question"),
    "Questionable Analogy": (A, "-> False Analogy"),
    "Questionable Cause": (A, "-> False Cause"),
    "Questionable Premise": (J, "premise plausibility is the reader's"),
    "Quibbling": (J, "dialogue-level"),
    "Quoting out of Context": (A, "-> Contextomy"),
    "Rationalization": (J, "psychology of the arguer"),
    "Red Herring": (J, "relevance across a dialogue"),
    "Refutation by Caricature": (A, "-> Straw Man"),
    "Regression": (C, "regression-is-the-null-after-an-extreme, practice family"),
    "Reification": (J, "category error"),
    "Reversing Causation": (V, "causal vocabulary; walton:correlation_to_cause exception"),
    "Scapegoating": (J, "ethotic"),
    "Scare Tactic": (J, "emotional appeal"),
    "Scope": (Z, "scope of operators over categorical forms; Z3 decides"),
    "Secundum Quid": (J, "SR census row; vocab there, a reader here without qualifiers"),
    "Selective Attention": (J, "in-graph half: counter-evidence-is-answered"),
    "Self-Fulfilling Prophecy": (J, "causal feedback in the world"),
    "Self-Selection": (V, "sample metadata; a-corpus-names-its-assembly reads the filed half"),
    "Sharpshooter's": (V, "prespecification: a-protocol-is-an-artifact-before-the-run"),
    "Slanting": (J, "in-graph half: counter-evidence-is-answered"),
    "Slippery Slope": (V, "walton:slippery_slope_base_case/inductive_step"),
    "Small Sample": (V, "sample metadata; calibration-size-is-declared-before-the-run"),
    "Smear Tactic": (A, "-> Ad Hominem"),
    "Smokescreen": (A, "-> Red Herring"),
    "Sorites": (A, "-> Heap"),
    "Special Pleading": (J, "exception without relevant difference; case vocabulary absent"),
    "Specificity": (J, "precision in prose; quantity half: a-figure-is-no-more-precise"),
    "Stacking the Deck": (J, "in-graph half: counter-evidence-is-answered"),
    "Stereotyping": (J, "group generalization in content"),
    "Straw Man": (J, "fidelity to an opponent's position; anchor covers the quotation half"),
    "Style Over Substance": (J, "presentation as warrant"),
    "Subjectivist": (J, "truth relativized to preference"),
    "Superstitious Thinking": (J, "causal belief without mechanism"),
    "Suppressed Evidence": (J, "in-graph half: counter-evidence-is-answered"),
    "Sweeping Generalization": (J, "SR accident/secundum-quid family"),
    "Syllogistic": (A, "-> Formal"),
    "Texas Sharpshooter's": (A, "-> Sharpshooter's"),
    "Tokenism": (J, "part offered as whole in content"),
    "Traditional Wisdom": (A, "-> Common Practice"),
    "Tu Quoque": (J, "ethotic; consistency of the arguer"),
    "Two Wrongs do not Make a Right": (J, "normative content"),
    "Undistributed Middle": (C, "Z3 refutes it; the derived form names it"),
    "Unfalsifiability": (J, "the estate's kill-criterion discipline is the filed half"),
    "Unrepresentative Sample": (V, "sample metadata; a-corpus-names-its-assembly"),
    "Unrepresentative Generalization": (A, "-> Unrepresentative Sample"),
    "Untestability": (A, "-> Unfalsifiability"),
    "Vested Interest": (J, "ethotic; walton:expert_opinion untrustworthy exception"),
    "Victory by Definition": (A, "-> Persuasive Definition"),
    "Willed ignorance": (J, "psychology of the arguer"),
    "Wishful Thinking": (J, "psychology of the arguer"),
    "You Too": (A, "-> Tu Quoque"),
}


def main() -> int:
    routes: dict[str, int] = {}
    for _, (route, _t) in CENSUS.items():
        routes[route] = routes.get(route, 0) + 1
    distinct = sum(1 for _, (r, _t) in CENSUS.items() if r != A)
    print(f"{SOURCE}: {len(CENSUS)} of the article's stated {SOURCE_COUNT} names")
    print()
    for r in (C, Z, V, J, A):
        print(f"  {r:<8} {routes.get(r, 0)}")
    print()
    print(f"  distinct patterns after collapsing aliases: {distinct}")
    print(f"  decidable now (covered+zero): "
          f"{routes.get(C, 0) + routes.get(Z, 0)} of {distinct}")
    if len(CENSUS) != SOURCE_COUNT:
        print(f"  NOTE: the fetched list yielded {len(CENSUS)} names against the "
              f"article's stated {SOURCE_COUNT}; the capture records the delta "
              "rather than papering over it.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
