"""Render the laws as markdown. `uv run python -m craft.render > LAWS.md`

The markdown is a VIEW. The data is the source of truth.

This matters more than it looks. The laws began life as a hand-written markdown file, and that
file contained a sentence saying three of its laws were unsourced — a sentence which was true,
which nobody would ever act on, and which no rule could read. Regenerating the prose from the
tree means the two can no longer disagree: if a law loses its citation, the rendered file says so
AND `craft.check` goes red, because both are reading the same node.

A consumer that needs the prose (a skill, a README, a plugin) ships the rendered file with the
rev it came from stamped on it, and re-renders rather than edits. Editing the view is how a view
becomes a second source of truth, and a second source of truth is how the sentence stopped
firing in the first place.

Two families render here. `laws.py` convicts a screen; `practice.py` convicts a way of working.
One file, because a reader who needs one usually needs the other, and a second file is a second
thing to forget to re-render.
"""

from __future__ import annotations

import io
import subprocess
import sys

from .laws import GATE, LAWS
from .practice import PRACTICE, PRACTICE_GATE


def _rev() -> str:
    try:
        out = subprocess.run(["git", "rev-parse", "--short", "HEAD"],
                             capture_output=True, text=True, check=True)
        return out.stdout.strip()
    except Exception:
        return "unknown"


def render() -> str:
    o = io.StringIO()
    w = o.write

    cited = [l for l in LAWS if l.params["authority"].grounded]
    uncited = [l for l in LAWS if not l.params["authority"].grounded]

    w("# Craft laws\n\n")
    w(f"<!-- GENERATED from craft@0.1.0 (xag/craft-laws@{_rev()}). Do not edit this file.\n")
    w("     Edit the laws in craft/laws.py and re-render: `python -m craft.render > LAWS.md`.\n")
    w("     Editing the view is how a view becomes a second source of truth. -->\n\n")
    w(f"{len(LAWS)} laws. **{len(cited)} cite a source. {len(uncited)} do not**, and are "
      "carried as hypotheses — visibly, and red in `craft.check`, until somebody sources them "
      "or deletes them.\n\n")
    w("Each law is stated as an observable, never as taste, so a verdict can be `fail` and not "
      "merely *I don't like it*. The **sightings** are the evidence: a law that has never caught "
      "anything is a law nobody should trust.\n\n")
    w("---\n\n")

    _render_laws(w, LAWS)

    w("---\n\n## The gate\n\n")
    w(f"{GATE.payload['note']}\n\n")

    p_cited = [l for l in PRACTICE if l.params["authority"].grounded]
    w("---\n\n# The practice\n\n")
    w(f"{len(PRACTICE)} laws about the WORK rather than about the interface. "
      f"**{len(p_cited)} cite a source.** They were earned in a single "
      "session by a single defect, which was declared finished fifteen times before it "
      "was.\n\n")
    _render_laws(w, PRACTICE)

    w("---\n\n## The practice gate\n\n")
    w(f"{PRACTICE_GATE.payload['note']}\n")
    return o.getvalue()


def _render_laws(w, laws) -> None:
    for law in laws:
        auth = law.params["authority"]
        flag = "" if auth.grounded else "  `UNCITED`"
        w(f"## {law.id.upper()}{flag}\n\n")
        w(f"{law.name}.\n\n")

        for k in law.children:
            if k.kind == "falsifier":
                w(f"- **Violated by:** {k.payload['claim']}\n")
        trig = [k.payload["when"] for k in law.children if k.kind == "trigger"]
        if trig:
            w(f"- **Switched on by:** {'; '.join(trig)}\n")

        cites = [k for k in law.children if k.kind == "citation"]
        if cites:
            for c in cites:
                w(f"- **Source:** [{c.name}]({c.payload['url']})\n")
                w(f"  > {c.payload['quote']}\n")
        else:
            w("- **Source:** none found. This law is an assertion, not an authority — treat it "
              "as a hypothesis.\n")

        for k in law.children:
            if k.kind == "sighting":
                w(f"- **Caught:** *{k.name}* — {k.payload['what']}\n")

        if law.payload.get("note"):
            w(f"\n{law.payload['note']}\n")
        w("\n")


if __name__ == "__main__":
    sys.stdout.reconfigure(encoding="utf-8")
    print(render())
